### ISSUE TITLE
Server only receives a single message from a client.

### ISSUE THREAD

**Issue by savant-martins** [PauSabatesC/SockNet#18]
Taking your example for client and server I created 2 x .Net Core console applications, both simply dump out messages sent/received to console.

Client sends a message once every X seconds.
The first message is received correctly by the server, the server responds.

All subsequent messages fail to reach the server.

**Comment by PauSabatesC** [comment]
Hi :)
Hmm that's weird, I'll try to replicate and test it but probably the problem comes from the message sent every X seconds. Have you tried the client method dispose() ?

**Comment by tamel123** [comment]
I have same problem , how i can wait for data in second  if (socketServer.IsNewData())

`                if (socketServer.IsNewData())
                {
                    Console.WriteLine("[LOG] Reseiving Data ");
                    var data = socketServer.GetData();
                    Task.Run(() => { Console.WriteLine(Encoding.UTF8.GetString(data.Value)); });
                    while (true)
                    {
                        Console.Write("\nEnter Command > ");
                        string mycommand = Console.ReadLine();
                        socketServer.ResponseToClient(data.Key, mycommand);
                        while (true)
                        {
                            if (socketServer.IsNewData())
                            {
                                var response = socketServer.GetData();
                                Console.WriteLine(Encoding.UTF8.GetString(response.Value));
                                break;
                            }

                        }

                    }

                }`

**Comment by PauSabatesC** [comment]
Hi,

This is now solved due to many petitions regarding this topic. But first of all it needs a clarification, the client does not has to keep closing or disconnecting from the socket connection to send new messages, you can reuse the same connection. Besides that now server will adapt to this multiple messages sent from the client and read and response to them.

This is now live in version 1.1.1 here https://www.nuget.org/packages/SockNet/

And the reference commit: https://github.com/PauSabatesC/SockNet/commit/3ea48595976fafb01956cb55e738849e6e88df44

Here I add an example of a client sending messages and a server:

Client: 
`byte[] recData = null;
            ISocketClient client = new SocketClient("127.0.0.1", 9999);

            try
            {
                if (await client.Connect())
                {
                    for (int i = 0; i < 7; i++)
                    {
                        await client.Send(data.ToArray());
                        byte[] STX1 = new byte[] { 0x02 };
                        byte[] ETX1 = new byte[] { 0x03 };

                        recData = await client.ReceiveNumberOfBytes(2, 8);
                        Console.WriteLine("Received data: " + Encoding.UTF8.GetString(recData));
                        Thread.Sleep(1000);
                    }
                }
            }
            catch (Exception e)
            {
                Console.WriteLine("Exception raised: " + e);
            }`

And the server:

`            byte[] STX = new byte[] { 0x02 };
            byte[] ETX = new byte[] { 0x03 };

            var socketServer = new SocketServer();
            socketServer.InitializeSocketServer("127.0.0.1", 9999);
            socketServer.SetReaderNumberOfBytes(2, 8);
            socketServer.StartListening();
            
            bool openServer = true;
            while (openServer)
            {
                if(socketServer.IsNewData())
                {
                    Console.WriteLine("new data arrived");
                    var data = socketServer.GetData();
                    // Do whatever you want with data
                    Task.Run(() => DoSomething(data, socketServer));
                }
            }

            socketServer.CloseServer();
`
